#!/bin/bash
echo "Script start!"
echo "Script by JasperTecHK, find it on my github!"
exec 2>/dev/null
        Init="1" 
        finalchk () {
		while ! [ $conf = "Y" ] 
			do
				echo "You have selected $call, correct? Y/N"
				read -sn 1 sel
			if [[ $sel =~ $inputnochk ]]; then
                        	 echo $errorinput
                   	elif [[ $sel = *"Y"* ]] || [[ $sel = *"y"* ]]; then
				conf="Y"
				Init="0"
				echo "Confirmed"
			elif [[ $sel = *"N"* ]] || [[ $sel = *"n"* ]]; then
				echo $rechoice
				conf="Y"
			else
				echo $errorinput
			fi
		done
			}
	while [ $Init -ne "0" ]
                do
                echo "Which list do you want to scour?"
			cat Options1
                read -sn 1 sel
		inputnochk='^[0-9]+$'
                errorinput="Error, Error! Invalid choice, dummy!" 
		rechoice="Fine, returning to start!" 
		conf="n"
                if ! [[ $sel =~ $inputnochk ]]; then
			echo $errorinput
                        elif [ $sel -eq "1" ]; then
				list="kantaiurl"
				end="_(kantai_collection)"
				nametxt="Kantai.csv"
				call="Kantai Collection"
                        elif [ $sel -eq "2" ]; then
         			list="azurlaneurl"
				end="_(azur_lane)"
				nametxt="Azur.csv"
				call="Azur Lane"
			elif [ $sel -eq "3" ]; then
				list="touhouurl"
				end=""
				nametxt="Touhou.csv"
				call="Touhou"
                        else
				echo "Wait. We haven't set this one up yet."
                        fi
			# if [ $sel -eq "0" ]; then
				#placeholder text.
			#else
				finalchk
			#fi
	done
        count=$(wc -l < "$list")
        head="1"
	count=$((count+1))
	url="https://danbooru.donmai.us/counts/posts?tags="
	namelocate="$PWD/Csv"
	if [ ! -d $namelocate ]; then
		mkdir Csv
	fi
	nametxt=($namelocate/$nametxt)
	if [ -f $nametxt ]; then
		rm $nametxt
	fi
        echo "Verbose mode? Y/N"
	read -sn 1 sel
	ttd=$SECONDS
	if [ $sel =~ $inputchk ]; then
		echo $errorinput
	elif [[ $sel = *"Y"* ]] || [[ $sel = *"y"* ]]; then
		echo "Confirmed."
		while [ $count -ne "0" ]
		do
			echo -ne "You have $count tag(s) left."\\r
			name=$(cat $list | head -n $head | tail -n 1 | sed $'s/\r//')
				urlt="$url$name"
				urlexe="$urlt$end"
				loop="0"
					while [ $loop -ne "2" ]
					do
					wget -O $name $urlexe
					result=$(sed -n -e '/Post count for/,$p' $name | head -n 2 | tail -n 1 | tr -d " \t\n\r")
						if [ $loop -eq "0" ]; then
							temphold="$result,"
							urlexe="$urlexe"+rating:s""
						else
							head=$((head+1))
							count=$((count-1))
							result="$temphold$result"
							echo $result >> $nametxt
							rm $name
						fi
				loop=$(($loop+1))
					done
		done
	elif [ $sel = "N" ] || [ $sel = "n" ]; then
		echo "Confirmed"
		while [ $count -ne "0" ]
		do
			echo -ne "You have $count tag(s) left."\\r
			name=$(cat $list | head -n $head | tail -n 1 | sed $'s/\r//')
				urlt="$url$name"
				urlexe="$urlt$end"
				loop="0"
					while [ $loop -ne "2" ]
					do
					wget -q -O $name $urlexe
					result=$(sed -n -e '/Post count for/,$p' $name | head -n 2 | tail -n 1 | tr -d " \t\n\r")
						if [ $loop -eq "0" ]; then
							temphold="$result,"
							urlexe="$urlexe"+ratings:s""
						else
							head=$((head+1))
							count=$((count-1))
							result="$temphold$result"
							echo $result >> $nametxt
							rm $name
						fi
				loop=$(($loop+1))
					done
		done
	else
		echo $errorinput
	fi
		ttd=$(($SECONDS-$ttd)) 
		xit="5"
		endcall="Script completed in $ttd seconds!"
		while [ $xit -ne "0" ]
		do
			echo -ne "$endcall Closing in $xit."\\r
			sleep 1
			xit=$((xit-1))
		done
	echo ""
exit
