#!/bin/bash

#Defining Functions
	sleep 3
	compute () {
		curl -s $1 | sed -n -e '/Post count for/,$p' | head -n 2 | tail -n 1 | tr -d " \t\n\r"
	}

	process () {
	cat temp | parallel --bar -v -k compute	#Due to the sensitive nature of the lists grabbed that require the results to come back in a specific order (Thus the whole point of the script...), -k is a hella useful feature! Parallel also seems to nearly scale perfectly with the number of cores you have in your system.
	}
	trigger () {
	process >> Hold
	sed 's/compute.*//' Hold >> $filehold	#Due to the way the script handles stuff, it kinda also exports a lot of junk. This is to clean the results of crap.
	sed -e 's/$/+rating:s/' -i temp		#Appending the modifier for final loop.
	echo "" > Hold				#Clearing out the temporary holding file.
	}
	export -f compute			#Parallel does subscripts per job, it seems. So just exporting all the functions, though realistically, I think I just need to export the compute Function.
	export -f process
	export -f trigger

#Start Script
	ttd=$SECONDS				#Timer start.
	Names=()				#Clearing all arrays of past data. May not be necessary? May be if loading multiple times?
	Impure=()
	Pure=()
	Ratio=()
	count=$(($count+1))
	for ((i=0; i<$count; i++))		#Adding in a ratio calculation.
	do
	expr $i + 2 >> ratio			#+2 because Array starts at 0, and need to skip the title line.
	done
	mapfile -t Ratio < ratio
	mapfile -t Names < $list		#Finally figured out Arrays, i think.
	for ((i=0; i<$count; i++))		#Finally got for loops working!
	do
	if [[ $end = "" ]]; then		#For some reason, it really hates dealing with underscores in variables. It just breaks url generation. So, to combat this, I'm injecting it later inside the subscript itself.
		echo ""$url${Names[$i]}"" >> temp
	else
		echo ""$url${Names[$i]}"_"$end"" >> temp
	fi
	done
	filehold="Impure"			#Impure numbers
	trigger
	sed -i '1,1d' Impure			#No idea why, but when you have multiple arrays, they seem to keep shifting themselves off by 1 per array generated. This is just to remove the whitespace before final array combination.
	filehold="Pure"				#Pure numbers
	trigger
	sed -i '1,2d' Pure			#Read comment above about Arrays.
	mapfile -t Impure < Impure		#Array Generation for combining.
	mapfile -t Pure < Pure
	echo "Name,Total,SFW,Purity %" >> $nametxt
	for ((i=0; i<$count; i++))		#Combining Arrays
	do
	if [[ ${Impure[$i]} = "0" ]]; then
		echo ${Names[$i]} >> nameerrors
	fi
		echo ""${Names[$i]}","${Impure[$i]}","${Pure[$i]}","=100-\(\(\$B${Ratio[$i]}-\$C${Ratio[i]}\)/\$B${Ratio[$i]}\)*100"" >> $nametxt
	done
	sed -i -e 's/^\(.\)/\U\1/' $nametxt	#Fixes Capitalization on each line
	ttd=$(($SECONDS-$ttd))
	echo "Script completed in $ttd seconds!"
	if [[ -f  nameerrors ]]; then
		echo "Errors in the url were detected. Perhaps those aren't the proper names? Check nameerrors file for list of errored links. Results were still added though."
	fi
	rm temp					#Cleanup of temp files
	rm Hold
	rm Impure
	rm Pure
	rm ratio
	sleep 3
